import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Lua Code!</h1>

        <br />

        <div className={styles.grid}>
          <Link href="/skillex">
            <a className={styles.card}>
              <h2> Skillex &rarr;</h2>
              <p> First layout of the training.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/marscapola"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with love by @marscapola
        </a>
      </footer>
    </div>
  );
}
